### ISSUE TITLE
Spaces inside parenthesis in :nth-child() causes sass-lint to hang

### ISSUE THREAD

**Issue by misund** [sasstools/sass-lint#1049]
## What version of Sass Lint are you using?
1.10.2

## Please include any relevant parts of your configuration
```yaml
# File Options
files:
  include: '*.s+(a|c)ss'

# Rule Configuration
rules:
  space-between-parens:
    - 2
    - include: true
```

## What did you do? Please include the actual source code causing the issue.
I changed the selector `:nth-child(2)` to `:nth-child( 2 )` (added spaces inside the parenthesis).

First run, where all is good:
```scss
// nth-child.scss
:nth-child(2) {
}
```

Second run, where sass-lint hangs:
```scss
// nth-child.scss
:nth-child( 2 ) {
}
```

![image](https://cloud.githubusercontent.com/assets/265459/24153566/1e52aae4-0e4f-11e7-96bc-75926a652bb6.png)

In case someone prefers plain text:
```
hades in ~/src/foo on master 
$ ./node_modules/sass-lint/bin/sass-lint.js --version
1.10.2
hades in ~/src/foo on master 
$ ./node_modules/sass-lint/bin/sass-lint.js -v

nth-child.scss
  1:11  error    Space expected at beginning of parenthesis  space-between-parens
  1:12  error    Space expected at end of parenthesis        space-between-parens
  1:15  warning  No empty blocks allowed                     no-empty-rulesets

✖ 3 problems (2 errors, 1 warning)


/home/misund/src/foo/node_modules/sass-lint/index.js:313
    throw new exceptions.SassLintFailureError(errorCount.count + ' errors were detected in \n- ' + errorCount.files.join('\n- '));
    ^
Error
    at Function.sassLint.failOnError (/home/misund/src/foo/node_modules/sass-lint/index.js:313:11)
    at detectPattern (/home/misund/src/foo/node_modules/sass-lint/bin/sass-lint.js:31:10)
    at Object.<anonymous> (/home/misund/src/foo/node_modules/sass-lint/bin/sass-lint.js:79:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
hades in ~/src/foo on master 
$ vim nth-child.scss 
hades in ~/src/foo on master* 
$ git diff
diff --git a/nth-child.scss b/nth-child.scss
index c635b41..db1192b 100644
--- a/nth-child.scss
+++ b/nth-child.scss
@@ -1,2 +1,2 @@
-:nth-child(2) {
+:nth-child( 2 ) {
 }
hades in ~/src/foo on master* 
$ ./node_modules/sass-lint/bin/sass-lint.js -v
```

## What did you expect to happen?
I expected the linter to finish the job, and then report warnings and errors.

## What actually happened? Please include any error messages given to you by Sass Lint.
The linter hangs and never gets done.

## If you're using a IDE plugin have you tried the CLI too?
Using the atom package, this causes my editor to freeze.

**Comment by bgriffith** [comment]
This is fixed in the newly released version v1.11.0. Please let me know if you still have issues. Thanks!
