### ISSUE TITLE
Error: Property Sort

### ISSUE THREAD

**Issue by minamarkham** [sasstools/sass-lint#13]
Property Sort  Order throws the following error:
```
/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/property-sort-order.js:73
              name = prop.first('ident').content;
                                        ^
TypeError: Cannot read property 'content' of undefined
    at /Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/property-sort-order.js:73:41
    at Node.forEach (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/basic-node.js:1:2053)
    at /Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/property-sort-order.js:71:15
    at RootNode.traverseByType (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
    at Object.module.exports.detect (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/property-sort-order.js:63:9)
    at /Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/index.js:50:25
    at Array.forEach (native)
    at Function.sassLint.lintText (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/index.js:49:9)
    at DestroyableTransform._transform (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/index.js:32:27)
    at DestroyableTransform.Transform._read (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
```

It seems to finish linting, but throws this error at the end.

**Comment by Snugug** [comment]
Do you have a reduced sample of Sass where this error is occouring?

**Comment by minamarkham** [comment]
I isolated the problem to my `_mixins.scss` and `_functions.scss` files, which don't actually have any selectors in them. Could that be the problem?

**Comment by Snugug** [comment]
Can you provide a concise example of where it's breaking?

**Comment by bgriffith** [comment]
As far as I can tell, it's caused by the assignment of a value to a variable within a function block.

```scss

@function test(foo) {
    // The line below causes the problem
    $bar: foo;
}
```

**Comment by minamarkham** [comment]
Here: 

```
@mixin placeholder {
  $placeholders: ":-webkit-input" ":-moz" "-moz" "-ms-input";
  @each $placeholder in $placeholders {
    &:#{$placeholder}-placeholder {
      @content;
    }
  }
}
``` 

and here

```
@function em($target, $context: $base-font-size) {
  @if not unitless($target) {
    $target: strip-units($target);
  }
  @if not unitless($context) {
    $context: strip-units($context);
  }
  @if $target == 0 { @return 0 }
  @return $target / $context + 0em;
}
```
