### ISSUE TITLE
Error: Space Between Parens

### ISSUE THREAD

**Issue by minamarkham** [sasstools/sass-lint#14]
When I turn on `space-between-parens`, I get the following error: 

```
/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/space-between-parens.js:40
        if (first.type === 'space') {
                 ^
TypeError: Cannot read property 'type' of undefined
    at /Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/space-between-parens.js:40:18
    at RootNode.traverseByType (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
    at Object.module.exports.detect (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/space-between-parens.js:15:9)
    at /Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/index.js:50:25
    at Array.forEach (native)
    at Function.sassLint.lintText (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/index.js:49:9)
    at DestroyableTransform._transform (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/index.js:32:27)
    at DestroyableTransform.Transform._read (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
```

and the linter exits without doing any checks.

**Comment by bgriffith** [comment]
Seems to get triggered when you have a function with no params.

```scss
// Function with params - No issue
@function bar($foo) {
    // ...
}

// Function with no params - causes issue
@function baz() {
    // ...
}
```
