### ISSUE TITLE
Indentation test failing on Windows (newline related?)

### ISSUE THREAD

**Issue by joshuacc** [sasstools/sass-lint#180]
I have the project checked out on Windows using Unix style line endings. Running `npm test` on develop I see the following failure:

```
1 failing

  1) indentation [size: 2]:

      AssertionError: 8 == 0
      + expected - actual

      -8
      +0

      at C:\Users\jclanton\Documents\GitHub\sass-lint\tests\rules\indentation.js:15:19
      at Object.module.exports.test (C:\Users\jclanton\Documents\GitHub\sass-lint\tests\rules\_lint.js:33:3)
      at Context.<anonymous> (C:\Users\jclanton\Documents\GitHub\sass-lint\tests\rules\indentation.js:12:10)
      at callFnAsync (C:\Users\jclanton\Documents\GitHub\sass-lint\node_modules\mocha\lib\runnable.js:306:8)
      at Test.Runnable.run (C:\Users\jclanton\Documents\GitHub\sass-lint\node_modules\mocha\lib\runnable.js:261:7)
      at Runner.runTest (C:\Users\jclanton\Documents\GitHub\sass-lint\node_modules\mocha\lib\runner.js:417:10)
      at C:\Users\jclanton\Documents\GitHub\sass-lint\node_modules\mocha\lib\runner.js:524:12
      at next (C:\Users\jclanton\Documents\GitHub\sass-lint\node_modules\mocha\lib\runner.js:338:14)
      at C:\Users\jclanton\Documents\GitHub\sass-lint\node_modules\mocha\lib\runner.js:348:7
      at next (C:\Users\jclanton\Documents\GitHub\sass-lint\node_modules\mocha\lib\runner.js:281:14)
      at Immediate._onImmediate (C:\Users\jclanton\Documents\GitHub\sass-lint\node_modules\mocha\lib\runner.js:316:5)
```

This may be related to how `os.EOL` is used in the indentation rule, but I have not yet had time to verify that.

**Comment by Snugug** [comment]
Did [your PR](https://github.com/sasstools/sass-lint/pull/154) not resolve this issue for you?

**Comment by DanPurdy** [comment]
This was left outstanding from that PR, it fixed EOL issues with a few of the other rules but indentation remains.
