### ISSUE TITLE
path must be a string

### ISSUE THREAD

**Issue by theskillwithin** [sasstools/sass-lint#185]
trying to use with SublimeText3 and I get this error in ST3 and Terminal:
➜  ~  sass-lint

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: path must be a string
    at Module.require (module.js:362:3)
    at require (module.js:380:17)
    at module.exports (/usr/local/lib/node_modules/sass-lint/lib/config.js:45:12)
    at Function.sassLint.getConfig (/usr/local/lib/node_modules/sass-lint/index.js:18:10)
    at Function.sassLint.lintFiles (/usr/local/lib/node_modules/sass-lint/index.js:63:18)
    at detectPattern (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:16:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:54:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by theskillwithin** [comment]
PS C:\Windows\system32> sass-lint

assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: missing path
    at Module.require (module.js:363:3)
    at require (module.js:384:17)
    at module.exports (C:\Users\Austin\AppData\Roaming\npm\node_modules\sass-lint\lib\config.js:45:12)
    at Function.sassLint.getConfig (C:\Users\Austin\AppData\Roaming\npm\node_modules\sass-lint\index.js:18:10)
    at Function.sassLint.lintFiles (C:\Users\Austin\AppData\Roaming\npm\node_modules\sass-lint\index.js:63:18)
    at detectPattern (C:\Users\Austin\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:16:18)
    at Object.<anonymous> (C:\Users\Austin\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:54:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by DanPurdy** [comment]
Where is your configuration file (.sass-lint.yml) in relation to your project and within which directory are you running your sass lint command?

**Comment by Snugug** [comment]
Are you using the [Sublime Linter plugin](https://github.com/skovhus/SublimeLinter-contrib-sass-lint)? Will it run if you just use the command line tool? If so, I believe this is an issue with the plugin

**Comment by theskillwithin** [comment]
Yes I am using the Sublime Linter Plugin and I noticed it wasn't working 
sass-lint failed: path must be a string
was the error I got

So the above was me just trying to run it in the terminal to get more detailed error.

I do not know what a .sass-lint.yml file is

**Comment by DanPurdy** [comment]
@theskillwithin the reason you are seeing this error then is because you don't have that configuration file in the root of your project directory.. Please read the configuration section of the readme... 

The .sass-lint.yml is a required file you must specify yourself to indicate which rules you would like active... Please see [here](https://github.com/sastools/sass-lint/blob/master/lib/config/sass-lint.yml) and [here] (ttps://github.com/sasstools/sass-lint/tree/master/docs) for more details! Dx

**Comment by DanPurdy** [comment]
Going to close this, no new info and looks like the config file was just missing.

**Comment by eseceve** [comment]
I've the same error when I run `sass-lint path/to/my.sass`

```
assert.js:92
  throw new assert.AssertionError({
            ^
AssertionError: path must be a string
    at Module.require (module.js:362:3)
    at require (module.js:380:17)
    at module.exports (/usr/lib/node_modules/sass-lint/lib/config.js:45:12)
    at Function.sassLint.getConfig (/usr/lib/node_modules/sass-lint/index.js:19:10)
    at Function.sassLint.lintFiles (/usr/lib/node_modules/sass-lint/index.js:35:28)
    at /usr/lib/node_modules/sass-lint/index.js:89:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (/usr/lib/node_modules/sass-lint/index.js:88:9)
    at detectPattern (/usr/lib/node_modules/sass-lint/bin/sass-lint.js:15:18)
    at /usr/lib/node_modules/sass-lint/index.js:89:21
```

version: 1.2.3
config: https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml
npm: 1.3.6
node: v0.10.36

**Comment by DanPurdy** [comment]
Try specifying the config file with the `-c path/to/my/.config.yml` and see if the same issue occurs it definitely looks like the config file is missing.

**Comment by Goz3rr** [comment]
I've made a file called `.sass-lint.yml` in my working directory, also where my scss file is and running `sass-lint style.scss` results in 

    assert.js:89
      throw new assert.AssertionError({
      ^
    AssertionError: missing path
        at Module.require (module.js:364:3)
        at require (module.js:385:17)
        at module.exports (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\lib\config.js:53:12)
        at Function.sassLint.getConfig (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:19:10)
        at Function.sassLint.lintText (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:35:28)
        at C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:89:21
        at Array.forEach (native)
        at Function.sassLint.lintFiles (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:88:9)
        at detectPattern (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:15:18)
        at C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:81:5

Manually specifying the config with `sass-lint -c .sass-lint.yml style.scss` results in

    C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\lib\rules.js:49
            throw new Error('Rule `' + rule + '` could not be found!');
            ^

    Error: Rule `placeholders-in-extend` could not be found!
        at C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\lib\rules.js:49:15
        at Array.forEach (native)
        at module.exports (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\lib\rules.js:27:29)
        at Function.sassLint.lintText (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:35:15)
        at C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:89:21
        at Array.forEach (native)
        at Function.sassLint.lintFiles (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:88:9)
        at detectPattern (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:15:18)
        at C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:81:5
        at Array.forEach (native)

This is the sample config as found [here](https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml)

After commenting out that line and running the previous command again I get:

    C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:57
                      'line': node.content[i + 1].start.line,
                                                 ^

    TypeError: Cannot read property 'start' of undefined
        at processNode (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:57:46)
        at processNode (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:96:9)
        at processNode (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:96:9)
        at Object.module.exports.detect (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:100:5)
        at C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:44:27
        at Array.forEach (native)
        at Function.sassLint.lintText (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:43:11)
        at C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:89:21
        at Array.forEach (native)
        at Function.sassLint.lintFiles (C:\Users\goz3rr\AppData\Roaming\npm\node_modules\sass-lint\index.js:88:9)

**Comment by DanPurdy** [comment]
Hi @Goz3rr 

Which version of `sass-lint` are you using? It looks like you might be using an older version hence why you're getting a warning about a missing rule. `sass-lint` is currently at version 1.3.2 You should try updating it.

As for the indentation rule error, are you using the `Sass` or `scss` syntax and are you using spaces or tabs within your file?

The indentation rule is due a little rewrite shortly for 2 reasons
* It doesn't fully work with the indented Sass syntax yet
* The AST we're using doesn't support tabs in the version we are using BUT the developer on that package is working hard to get all of our current issues sorted and we should be updating soon!

We've decided to leave the indentation rule 'half-working' for now in order to get a proper rewrite once the tab issue with the AST is resolved.

Hope that helps, let me know if that's not the problem though!

**Comment by eseceve** [comment]
It works for me with `-c`. Thanks @DanPurdy =)

**Comment by Goz3rr** [comment]
I've installed sass-lint this morning from npm and it's version 1.3.1. How would I go about installing version 1.3.2?

I'm using scss syntax with tabs so that might be the issue here, I'll try changing to spaces and see what happens

**Comment by DanPurdy** [comment]
Apologies @Goz3rr I'm getting ahead of myself there, we plan on releasing 1.3.2 today... :smile: 

1.3.1 is the latest. Yeah I would hazard a guess that tabs is your problem right now, as I said we'll be looking to fix the issue with tabs as soon as we can!

@eseceve Great! If you run sass-lint from the CLI you can specify the path to the config file or just make sure you run it from within the directory containing the config file anyway. Glad it worked for you!
