### ISSUE TITLE
Error trying to lint scss file with Node v4.1.0

### ISSUE THREAD

**Issue by davegomez** [sasstools/sass-lint#197]
I'm getting this error when I try to lint a file using sass-lint with Node v4.1.0

```
$ sass-lint -v path-to-file
undefined:2
path-to-file
^

SyntaxError: Unexpected token
                                  at Object.parse (native)
    at Function.sassLint.resultCount (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/index.js:23:26)
    at Function.sassLint.outputResults (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/index.js:110:12)
    at detectPattern (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/bin/sass-lint.js:21:10)
    at /Users/user/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/bin/sass-lint.js:58:5
    at Array.forEach (native)
    at Object.<anonymous> (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/bin/sass-lint.js:57:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```

**Comment by bgriffith** [comment]
Are you running Sass-lint 1.2.1? If not can you update and let me know if the problem persists.

**Comment by davegomez** [comment]
This is another error I just got using sass-lint on my office laptop.

```
sass-lint lib
fs.js:603
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at /Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/index.js:88:18
    at Array.forEach (native)
    at Function.sassLint.lintFiles (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/index.js:86:9)
    at detectPattern (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/bin/sass-lint.js:16:18)
    at /Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/bin/sass-lint.js:58:5
    at Array.forEach (native)
    at Object.<anonymous> (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/bin/sass-lint.js:57:16)
```

I'm using `sass-lint v1.2.1` on both of them with Node v4.1.0 as I told you before.

BTW, I didn't get any compilation/installation error

**Comment by DanPurdy** [comment]
That's an illegal operation on a directory.. can you paste the exact command you are using?
It looks like you may be pointing the linter at a directory rather than a `.scss` or `.sass` file.

**Comment by davegomez** [comment]
Is true, I did it over a directory (thought I could) but this is the error when I try to lint a scss file.

```
sass-lint file.scss -v
undefined:2
file.scss
^

SyntaxError: Unexpected token 
                                  at Object.parse (native)
    at Function.sassLint.resultCount (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/index.js:23:26)
    at Function.sassLint.outputResults (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/index.js:110:12)
    at detectPattern (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/bin/sass-lint.js:21:10)
    at /Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/bin/sass-lint.js:58:5
    at Array.forEach (native)
    at Object.<anonymous> (/Users/dave/.nvm/versions/node/v4.1.0/lib/node_modules/sass-lint/bin/sass-lint.js:57:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```

**Comment by DanPurdy** [comment]
I just checked, if you specify a path to lint with the CLI it ignores the file globbing options you have set in `sass-lint.yml` as expected. If this is a directory then unfortunately it will break, an improvement would be to then scan this directory taking into account any ignored paths.

Could you provide a copy of your `.sass-lint.yml` and a rough outline of your projects structure?

**Comment by DanPurdy** [comment]
Never mind I just recreated with this

`sass-lint -c /usr/local/lib/node_modules/sass-lint/lib/config/sass-lint.yml public/app/scss/main.scss -v`

```undefined:0


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Function.sassLint.resultCount (/usr/local/lib/node_modules/sass-lint/index.js:23:26)
    at Function.sassLint.outputResults (/usr/local/lib/node_modules/sass-lint/index.js:110:12)
    at detectPattern (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:21:10)
    at /usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:58:5
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:57:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

Will look into it :)

**Comment by davegomez** [comment]
👍

**Comment by DanPurdy** [comment]
Can you expand a little here, I've not tried using this with webpack yet. How're you configuring it, what is sasslint-loader and how is the project setup?

Thanks

Dan

**Comment by davegomez** [comment]
[sasslint-loader](https://github.com/alleyinteractive/sasslint-loader) is just a small sass-lint loader for Webpack. The configuration is very straight forward using the preloader or loader syntax from Webpack.

```
{
    test: /\.js$/,
    exclude: /node_modules/,
    loader: 'sasslint'
}
```

Nothing fancy here...

**Comment by DanPurdy** [comment]
Hmm ok, had never seen that webpack loader before.. I don't think this is related though.

**Comment by DanPurdy** [comment]
@davegomez we've released `1.2.2` which addresses your original issue. I'll close this issue now. If you encounter any further problems please open another issue.

Thanks again.

**Comment by davegomez** [comment]
Perfect @DanPurdy, I will test it today and I will let you know if I find any other issue.

**Comment by dsnoeck** [comment]
@davegomez Were you able to use it with webpack ? I'm looking for a sass-lint loader.

**Comment by davegomez** [comment]
@dsnoeck sass-lint is working perfectly, sadly the sasslint-loader doesn't work at all and the dev sasslint-loader dev team has failed miserably on fixing the bugs, they have not even pushed the module to NPM.

I've been thinking about writing one myself.
