### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by davidosomething** [sasstools/sass-lint#357]
v1.3.1
node v0.12.7
Running from CLI gives me this:

```
/Users/david/.config/.nvm/versions/node/v0.12.7/lib/node_modules/sass-lint/lib/rules/trailing-semicolon.js:29
            if (next.type === 'declarationDelimiter') {
                    ^
TypeError: Cannot read property 'type' of undefined
    at /Users/david/.config/.nvm/versions/node/v0.12.7/lib/node_modules/sass-lint/lib/rules/trailing-semicolon.js:29:21
    at Node.forEach (/Users/david/.config/.nvm/versions/node/v0.12.7/lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/basic-node.js:1:2053)
    at /Users/david/.config/.nvm/versions/node/v0.12.7/lib/node_modules/sass-lint/lib/rules/trailing-semicolon.js:25:15
    at RootNode.traverseByType (/Users/david/.config/.nvm/versions/node/v0.12.7/lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
    at Object.module.exports.detect (/Users/david/.config/.nvm/versions/node/v0.12.7/lib/node_modules/sass-lint/lib/rules/trailing-semicolon.js:14:11)
    at /Users/david/.config/.nvm/versions/node/v0.12.7/lib/node_modules/sass-lint/index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (/Users/david/.config/.nvm/versions/node/v0.12.7/lib/node_modules/sass-lint/index.js:43:11)
    at /Users/david/.config/.nvm/versions/node/v0.12.7/lib/node_modules/sass-lint/index.js:89:21
    at Array.forEach (native)

```

**Comment by BPScott** [comment]
Hi @davidosomething, have you got a minimal test case containing the sass code you''re running sass-lint against so we can reproduce this?

**Comment by davidosomething** [comment]
I can't reproduce this exact one from a clean slate, but here's some output of me trying on this minimal codebase:

```
david@elitedavid:~/projects/sasslint-test
14:29:08I% node --version && npm --version && ./node_modules/sass-lint/bin/sass-lint.js --version
v0.12.7
3.3.5
1.3.1
david@elitedavid:~/projects/sasslint-test
14:29:18I% ./node_modules/sass-lint/bin/sass-lint.js sass/main.scss
/Users/david/projects/sasslint-test/node_modules/sass-lint/index.js:141
      throw new Error(result.errorCount + ' errors detected in ' + result.file
            ^
Error: 1 errors detected in sass/main.scss
    at Function.sassLint.failOnError (/Users/david/projects/sasslint-test/node_modules/sass-lint/index.js:141:13)
    at detectPattern (/Users/david/projects/sasslint-test/node_modules/sass-lint/bin/sass-lint.js:22:10)
    at /Users/david/projects/sasslint-test/node_modules/sass-lint/bin/sass-lint.js:81:5
    at Array.forEach (native)
    at Object.<anonymous> (/Users/david/projects/sasslint-test/node_modules/sass-lint/bin/sass-lint.js:80:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
david@elitedavid:~/projects/sasslint-test
14:29:19I%
```

https://github.com/davidosomething/sasslint-test/
clone, npm install, `./node_modules/sass-lint/bin/sass-lint.js sass/main.scss`

**Comment by davidosomething** [comment]
never mind -- got it to work, it was reporting that original error in the first post when the src is not defined properly in grunt-sass-lint

**Comment by bgriffith** [comment]
Glad you got it working. Going to close this.
