### ISSUE TITLE
A simple variable declaration is causing "Please check validity of the block starting from line"

### ISSUE THREAD

**Issue by gajus** [sasstools/sass-lint#358]
I have a file:

```css
$primary-color: #333;
```

Linting this file produces the following error message:

```
/Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/sass-lint/lib/groot.js:21
    throw new Error('Parsing error' + fileInfo + ': ' + e.message);
    ^

Error: Parsing error at <text>: Please check validity of the block starting from line #1
    at module.exports (/Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/sass-lint/lib/groot.js:21:11)
    at Function.sassLint.lintText (/Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/sass-lint/index.js:36:13)
    at exports.lintText.lintText (/Users/gajus/Documents/dev/canonical-code-style/canonical/dist/linters/scss/index.js:26:36)
    at exports.lintText.lintText (/Users/gajus/Documents/dev/canonical-code-style/canonical/dist/index.js:82:44)
    at /Users/gajus/Documents/dev/canonical-code-style/canonical/dist/index.js:121:22
    at arrayEach (/Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/lodash/index.js:3345:13)
    at exports.lintFiles.lintFiles (/Users/gajus/Documents/dev/canonical-code-style/canonical/dist/index.js:109:25)
    at Object.<anonymous> (/Users/gajus/Documents/dev/canonical-code-style/canonical/dist/bin/index.js:86:27)
    at Module._compile (module.js:435:26)
```

**Comment by DanPurdy** [comment]
@gajus there must be something else going on here, this parses fine and we've got this declaration in multiple tests too.

**Comment by gajus** [comment]
I am tracing the issue.

It appears that `groot` function is being executed with `syntax` `undefined`.

**Comment by gajus** [comment]
This is how I am using `sass-lint`:

```js
let report;

report = SassLinter.lintText({
    text: text,
    filename: '<text>'
}, {}, path.resolve(__dirname, '.sass-lint.yml'));

return report;
```

Is this missing "syntax" property somewhere? I cannot find docs for `lintText`

**Comment by DanPurdy** [comment]
what else do you have in the file Sass file? If you're getting that error it's because something either isn't right in your Sass file or you're using tabs..

**Comment by gajus** [comment]
Thats literally all there is in that file.

**Comment by gajus** [comment]
Ok, a potential issue is that I am not defining `file.format` property, which is being passed to `groot` https://github.com/sasstools/sass-lint/blob/develop/index.js#L36. Though, I cannot see documentation for that property.

**Comment by gajus** [comment]
Based on this https://github.com/sasstools/sass-lint/blob/develop/index.js#L91, I am guessing it needs to be SCSS or SASS.

**Comment by gajus** [comment]
Yup, setting it to "scss" fixes it. Some documentation on how to use `lintText` would not hurt.

**Comment by DanPurdy** [comment]
Agreed, this is a fairly young project though and we'll be looking to improve the whole inner working in 2.0 which isn't too far on the horizon.

**Comment by gajus** [comment]
It is a great piece of software. Thank you.

**Comment by ahiipsa** [comment]
I had some error with validate scss in .css file by using cli:
**--syntax scss** save me %)
```
sass-lint --syntax scss --format stylish --verbose -q css/mobile/vars.css 
```
