### ISSUE TITLE
Node 4.1.2, start of undefined

### ISSUE THREAD

**Issue by robertbaker** [sasstools/sass-lint#373]
```
TypeError: Cannot read property 'start' of undefined
    at processNode (c:\git\pos\node_modules\sass-lint\lib\rules\indentation.js:57:46)
    at processNode (c:\git\pos\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (c:\git\pos\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at Object.module.exports.detect (c:\git\pos\node_modules\sass-lint\lib\rules\indentation.js:100:5)
    at c:\git\pos\node_modules\sass-lint\index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (c:\git\pos\node_modules\sass-lint\index.js:43:11)
    at DestroyableTransform._transform (c:\git\pos\node_modules\gulp-sass-lint\index.js:32:27)
    at DestroyableTransform.Transform._read (c:\git\pos\node_modules\gulp-sass-lint\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (c:\git\pos\node_modules\gulp-sass-lint\node_modules\readable-stream\lib\_stream_transform.js:160:12)
```

**Comment by DanPurdy** [comment]
Are you using tabs in your project?

If so see #62

**Comment by robertbaker** [comment]
@DanPurdy no, spaces all the way!

**Comment by DanPurdy** [comment]
Would you mind trying to narrow down the code that this is occurring on then please? Just so we can see what is causing it.

**Comment by robertbaker** [comment]
Seems to be failing on all files.

**Comment by robertbaker** [comment]
Ran it directly via CLI

```
TypeError: Cannot read property 'start' of undefined
    at processNode (C:\Users\rbaker\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:57:46)
    at processNode (C:\Users\rbaker\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at processNode (C:\Users\rbaker\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:96:9)
    at Object.module.exports.detect (C:\Users\rbaker\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:100:5)
    at C:\Users\rbaker\AppData\Roaming\npm\node_modules\sass-lint\index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (C:\Users\rbaker\AppData\Roaming\npm\node_modules\sass-lint\index.js:43:11)
    at C:\Users\rbaker\AppData\Roaming\npm\node_modules\sass-lint\index.js:91:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (C:\Users\rbaker\AppData\Roaming\npm\node_modules\sass-lint\index.js:90:9)
```

**Comment by DanPurdy** [comment]
Would you mind zipping up the project files and sending them to me? I can hopefully debug it then and work out what this is.

**Comment by DanPurdy** [comment]
Or pushing them up to github somewhere! I forget we don't need floppy disks to share files some days! :smile:

**Comment by robertbaker** [comment]
@DanPurdy Are you using node 4.1.3? If not can you try it?

I know it's failing on indentation, but I doubt it's a file doing it. 

```
C:\Users\rbaker\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\indentation.js:57
                  'line': node.content[i + 1].start.line,
                                             ^
```

**Comment by DanPurdy** [comment]
Our indentation tests are passing against node 4.2.2

wait.. are you using scss or Sass ?

**Comment by robertbaker** [comment]
scss

**Comment by DanPurdy** [comment]
I need to get hold of your code then and try and work out what's going on If that's possible, if you say it's happening on every file then any of them will do. I'm at a loss to say what's wrong until then.. Can you also just confirm which version of sass-lint you're using.

**Comment by robertbaker** [comment]
node-sass@^3.4.1

https://drive.google.com/file/d/0ByFZyanaAvZDUmhZQWdaU3NybTA/view?usp=sharing

**Comment by DanPurdy** [comment]
Hi @robertbaker,

Thanks for this, I've finally got round to looking at this and can confirm there is a bug in the indentation rule due to the CRLF line endings you're using in that file. I've created another issue which has a bit more information on the direct issue to be resolved so I'm going to close this issue in an effort to keep things manageable, you can find that issue here #382.

Thanks again for taking the time to follow up on this, hopefully this will be resolved fairly soon!
