### ISSUE TITLE
Parser chokes on concatenated properties

### ISSUE THREAD

**Issue by kaelig** [sasstools/sass-lint#386]
Using sass-lint cli 1.3.2.

```scss
.test {
  #{$property}-#{$position}: #{$size};
}
```

Returns an error with this stacktrace:

```
/Users/kdeloumeauprigent/workspace/salesforce/design-system-internal/node_modules/sass-lint/lib/groot.js:21
    throw new Error('Parsing error' + fileInfo + ': ' + e.message);
    ^

Error: Parsing error at ui/dependencies/layout.scss: Please check validity of the block starting from line #327
    at module.exports (/Users/kdeloumeauprigent/workspace/salesforce/design-system-internal/node_modules/sass-lint/lib/groot.js:21:11)
    at Function.sassLint.lintText (/Users/kdeloumeauprigent/workspace/salesforce/design-system-internal/node_modules/sass-lint/index.js:36:13)
    at /Users/kdeloumeauprigent/workspace/salesforce/design-system-internal/node_modules/sass-lint/index.js:91:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (/Users/kdeloumeauprigent/workspace/salesforce/design-system-internal/node_modules/sass-lint/index.js:90:9)
    at detectPattern (/Users/kdeloumeauprigent/workspace/salesforce/design-system-internal/node_modules/sass-lint/bin/sass-lint.js:15:18)
    at Object.<anonymous> (/Users/kdeloumeauprigent/workspace/salesforce/design-system-internal/node_modules/sass-lint/bin/sass-lint.js:77:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

**Comment by DanPurdy** [comment]
HI @kaelig unfortunately this is a known issue with the current version of our AST we're just waiting for it to update at the moment. You can find this issue in more detail here #44 .

Going to close this issue to keep all talk in that issue.

**Comment by kaelig** [comment]
Oops, sorry. I wasn't sure if it was Gonzales or sass-lint.

**Comment by DanPurdy** [comment]
That's ok no worries, if it comes up as a parse error it's usually a gonzales issue but we aren't using the latest version of that yet as it's latest updates have introduced some unfortunate regressions and there are some outstanding issues too. Once it's updated though we will be moving to integrate it as soon as we can.
