### ISSUE TITLE
Cannot read property 'content' of undefined when @extend from external file

### ISSUE THREAD

**Issue by itsimoshka** [sasstools/sass-lint#396]
`Sass-lint` crashes when encounter `@extend` from external file.
For example I use PureCSS, and 
```
.test
  @extend .pure-u-1-6
```

In this case I get Cannot read property 'content'  error

**Comment by bgriffith** [comment]
Can you give us the whole error please? So we can see which rule is causing the issue.

**Comment by itsimoshka** [comment]
```
mixin-name-format.js:25
        name = node.first('simpleSelector').first('ident').content;
                                                          ^

TypeError: Cannot read property 'content' of undefined
    at C:\Users\its\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\mixin-name-format.js:25:59
    at RootNode.traverseByType (C:\Users\its\AppData\Roaming\npm\node_modules\sass-lint\node_modules\gonzales-pe\lib\node\root-node.js:1:1739)
    at RootNode.traverseByTypes (C:\Users\its\AppData\Roaming\npm\node_modules\sass-lint\node_modules\gonzales-pe\lib\node\root-node.js:1:1937)
    at Object.module.exports.detect (C:\Users\its\AppData\Roaming\npm\node_modules\sass-lint\lib\rules\mixin-name-format.js:16:9)
    at C:\Users\its\AppData\Roaming\npm\node_modules\sass-lint\index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (C:\Users\its\AppData\Roaming\npm\node_modules\sass-lint\index.js:43:11)
    at C:\Users\its\AppData\Roaming\npm\node_modules\sass-lint\index.js:91:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (C:\Users\its\AppData\Roaming\npm\node_modules\sass-lint\index.js:90:9)
```

**Comment by bgriffith** [comment]
Awesome thanks.

**Comment by itsimoshka** [comment]
@bgriffith now I see that problem is in name, but why I can't extend class?

**Comment by bgriffith** [comment]
There's a bug that's assuming a certain node exists. You should be able to extend classes. We'll hotfix this.
