### ISSUE TITLE
Running sass-lint fails on Windows 7 (sass-lint 0.1.0-beta.2)

### ISSUE THREAD

**Issue by joshuacc** [sasstools/sass-lint#41]
I have tried both global and local installs. In either case, invoking the `sass-lint` command produces the following:

```
C:\project-path>sass-lint
module.js:338
    throw err;
          ^
Error: Cannot find module '../lib/sass-lint'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\jclanton\AppData\Roaming\npm\node_modules\sass-lint\bin\sass-lint.js:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

I do not have this problem with any other packages.

**Comment by Snugug** [comment]
There is no CLI yet. You cannot run `sass-lint` from the command line like you are doing and have it work. That was postponed until after the first release in favor of task runner integration.

**Comment by joshuacc** [comment]
@Snugug Ah. That would explain it. I saw that sass-lint had installed a command into `node_modules/.bin/` and assumed that it would work.

I'll give the Gulp plugin a try. Thanks!

**Comment by Snugug** [comment]
We started working on it, but abandoned it initially to get the functionality out the door.

**Comment by Snugug** [comment]
You can track progress on the CLI here:
42
