### ISSUE TITLE
empty-line-between-blocks sass issue

### ISSUE THREAD

**Issue by DanPurdy** [sasstools/sass-lint#447]
Another `.sass` format issue this time with the `empty-line-between-blocks` rule. Again as a result of looking into #437 

```
/Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:67
    if (previous.is('space') || previous.is('declarationDelimiter')) {
                 ^

TypeError: previous.is is not a function
    at findNearestReturnSass (/Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:67:18)
    at findNearestReturnSass (/Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:82:14)
    at /Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:175:27
    at Node.forEach (/Users/danpurdy/workspace/sass-lint/node_modules/gonzales-pe/lib/node/basic-node.js:1:2053)
    at /Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:155:16
    at RootNode.traverseByType (/Users/danpurdy/workspace/sass-lint/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
    at Object.module.exports.detect (/Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:118:9)
    at /Users/danpurdy/workspace/sass-lint/index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (/Users/danpurdy/workspace/sass-lint/index.js:43:11)
```

To recreate run the rule against the mixins-before-declarations `.sass` [test file](https://github.com/sasstools/sass-lint/blob/develop/tests/sass/mixins-before-declarations.sass)

reported in sass-lint: 1.3.3

**Comment by bgriffith** [comment]
I don't think this is still an issue when using the latest gonzales.

**Comment by indiesquidge** [comment]
@DanPurdy @bgriffith I am also getting this issue (sass-lint: 1.5.1)

**Comment by DanPurdy** [comment]
The example above is fixed in sass-lint 1.6.0
@indiesquidge

**Comment by sawyerh** [comment]
I just ran into this on sass-lint 1.7.0. Seemed to fail after the include here:

```sass
.foo
  @include clearfix
  .bar
    width: 32%
```

The `clearfix` mixin looks like:

```sass
@mixin clearfix
  zoom: 1

  &:before, &:after
    content: ""
    display: table

  &:after
    clear: both
```

Changing to this (space after `@include`) fixed the error:

```
```sass
.foo
  @include clearfix

  .bar
    width: 32%
```
```

**Comment by DanPurdy** [comment]
Hey @sawyerh Could you make a new issue with this please, it's easier for us to track and fix these after the issue is closed. Thanks!
