### ISSUE TITLE
CLI is broken?

### ISSUE THREAD

**Issue by gvn** [sasstools/sass-lint#500]
I have Node v5.5.0 running on OS X 10.11.3.

Repro:

1. `npm install sass-lint -g`
2. `sass-lint`

Results:

```bash
/usr/local/lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/basic-node.js:1
(function (exports, require, module, __filename, __dirname) { 'use strict';var _createClass=(function(){function defineProperties(target, props){for(var i=0; i < props.length; i++) {var descriptor=props[i];descriptor.enumerable = descriptor.enumerable || false;descriptor.configurable = true;if('value' in descriptor)descriptor.writable = true;Object.defineProperty(target, descriptor.key, descriptor);}}return function(Constructor, protoProps, staticProps){if(protoProps)defineProperties(Constructor.prototype, protoProps);if(staticProps)defineProperties(Constructor, staticProps);return Constructor;};})();function _classCallCheck(instance, Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function');}}var Node=(function(){function Node(options){_classCallCheck(this, Node);this.type = options.type;this.content = options.content;this.syntax = options.syntax;if(options.start)this.s

TypeError: Cannot read property 'type' of undefined
    at Node.last (/usr/local/lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/basic-node.js:1:2641)
    at Object.module.exports.detect (/usr/local/lib/node_modules/sass-lint/lib/rules/final-newline.js:19:23)
    at /usr/local/lib/node_modules/sass-lint/index.js:123:27
    at Array.forEach (native)
    at Function.sassLint.lintText (/usr/local/lib/node_modules/sass-lint/index.js:122:11)
    at /usr/local/lib/node_modules/sass-lint/index.js:179:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (/usr/local/lib/node_modules/sass-lint/index.js:178:9)
    at detectPattern (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:16:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:87:3)
```

Expected: Something less broken?

Apologies if this is already filed...thanks for your work!

**Comment by DanPurdy** [comment]
How're you running this are you in a folder with a .sass-lint.yml file? You're not specifying any cli flags so im assuming you must be running this from your project root?

Are you using `.scss` or `.sass` syntax? Can you try running it directly against one file in your project and specify a config file etc

Any extra info you can provide will be helpful. Our CLI is passing all our tests and i've been using it today without issue so it'd be good to get to the bottom of the cause.

**Comment by gvn** [comment]
I'll see if I can sandbox some of this, but right now if I run `sass-lint` (1.5.0 installed via `npm install sass-lint -g`) in an empty folder it throws:

```bash
 sass-sandbox  ▶ sass-lint

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: missing path
    at Module.require (module.js:365:3)
    at require (internal/module.js:16:19)
    at module.exports (/usr/local/lib/node_modules/sass-lint/lib/config.js:73:12)
    at Function.sassLint.getConfig (/usr/local/lib/node_modules/sass-lint/index.js:25:10)
    at Function.sassLint.lintFiles (/usr/local/lib/node_modules/sass-lint/index.js:166:18)
    at detectPattern (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:16:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:87:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by gvn** [comment]
Here's a more robust but sandboxed example with a directory w. 2 files:

`sample.sass`
```sass
#foo
  padding: 10px
```

`.sass-lint.yml`
```yaml
files:
  include: 'sample.sass'
rules:
  no-ids: 2
```

Now, if I run `sass-lint -c .sass-lint.yml` I get the following:

```bash
 sass-sandbox  ▶ sass-lint -c .sass-lint.yml
/usr/local/lib/node_modules/sass-lint/index.js:250
    throw new Error(errorCount.count + ' errors were detected in \n- ' + errorCount.files.join('\n- '));
    ^

Error: 1 errors were detected in
- sample.sass
    at Function.sassLint.failOnError (/usr/local/lib/node_modules/sass-lint/index.js:250:11)
    at detectPattern (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:27:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:87:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

Hopefully that's helpful...

**Comment by DanPurdy** [comment]
Ok so the issue here is that you have your rule severity set to 2 which is an error but you're not using the -q flag or --no-exit which means the first lint match for your rule with throw an error.. If you use the flag I mentioned it will probably give you what you expect as it won't kill the process on the first severity 2 lint error you encounter. Let me know if that helps

**Comment by gvn** [comment]
Ok, interesting. It looks like if I run `sass-lint -c .sass-lint.yml --no-exit -v` then I get a report on errors found in the Sass code, which is what I'd expect for baseline functionality. Thanks, that wasn't intuitive unfortunately.

I guess this is by design, but it seems like the linter itself shouldn't throw JS errors when it hits a linting issue in its target Sass. It appeared that the linter was broken as is.

Also, an argument free call to `sass-lint` calling `sass-lint --help` would probably be more clean and less broken feeling than throwing an error...I could see about making a PR if that makes sense.

Thanks for your help!

**Comment by DanPurdy** [comment]
Yeah I agree, I've got plans to change its baseline functionality for sass-lint v2 but having it call the help method on an empty call for now would probably be a decent half way. Glad its solved for you :+1:

**Comment by jjalonso** [comment]
Same error here. 

Im on a folder that contain package.json with sasslintConfig: '.sasslint.yml'  and the YML is there also.

**Comment by DanPurdy** [comment]
That's a big in the indentation rule it's not to do with the CLI unfortunately.. Try turning that rule off and see what happens. I imagine seen as you were commenting about using tabs in another issue that this will be your problem for now.

Once we release 1.6 we'll hopefully be able to take a little more of an indepth look into this issue

**Comment by jjalonso** [comment]
We should wait because use the linter without indent tab is pointless.
