### ISSUE TITLE
Nested element in element#id selector gives parse error.

### ISSUE THREAD

**Issue by vhaarr** [sasstools/sass-lint#560]
Hi,

So I believe I've stumbled upon 2 seperate issues, but I am not filing them as such because I am not sure if this is the correct place to file them, and if it is, they might both be configuration mistakes on my part.

The first is that when I run sass-lint directly from the tty, this happens:
`$ sass-lint _appstyles.scss
/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:57
                  'line': node.content[i + 1].start.line,
                                             ^

TypeError: Cannot read property 'start' of undefined
    at processNode (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:57:46)
    at processNode (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at processNode (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at processNode (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at processNode (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at processNode (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at processNode (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:96:9)
    at Object.module.exports.detect (/usr/local/lib/node_modules/sass-lint/lib/rules/indentation.js:100:5)
    at /usr/local/lib/node_modules/sass-lint/index.js:123:27
    at Array.forEach (native)`

The other issue is that when I use it through https://github.com/AtomLinter/linter-sass-lint 1.1.1 in either Atom 1.5.3 or 1.6.0-beta6, it produces this error:
"Unexpected parse error in fileat line 1 col 1"

On the following sass:
`
section#prosjekter {
article {}
}
`

**Comment by bgriffith** [comment]
Hi @vhaarr - Thanks for the report. Are you using tabs by any chance?

If so, there's an issue with 1.5 that will soon be fixed with the soon to be released `v1.6`

**Comment by vhaarr** [comment]
Yes, I use tabs for indentation.
Would that cause both problems?

**Comment by DanPurdy** [comment]
It looks like it. There was an issue in the AST we use, gonzales-pe which looks to be fixed now. We've just finished updating all of our rules for the latest version so fingers crossed everything should be sorted in 1.6 :+1:  though this may just open more issues with the indentation rule which requires further work.

**Comment by ivanakimov** [comment]
+1

**Comment by DanPurdy** [comment]
This example is no longer throwing an error in sass-lint 1.6.0 though the indentation rule is still to be updated and fixed to work correctly so we can't guarantee it's accuracy right now. 

Will close this as we have indentation issues open already and the updates are in the pipeline but the underlying reason for this error to be thrown has been solved.
