### ISSUE TITLE
empty-line-between-blocks sass issue

### ISSUE THREAD

**Issue by sawyerh** [sasstools/sass-lint#729]
Running into the same error as #447 (included below), except this is on version 1.7.0, which was after the [original fix](https://github.com/sasstools/sass-lint/issues/447#issuecomment-213361113).

```
/Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:67
    if (previous.is('space') || previous.is('declarationDelimiter')) {
                 ^

TypeError: previous.is is not a function
    at findNearestReturnSass (/Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:67:18)
    at findNearestReturnSass (/Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:82:14)
    at /Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:175:27
    at Node.forEach (/Users/danpurdy/workspace/sass-lint/node_modules/gonzales-pe/lib/node/basic-node.js:1:2053)
    at /Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:155:16
    at RootNode.traverseByType (/Users/danpurdy/workspace/sass-lint/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
    at Object.module.exports.detect (/Users/danpurdy/workspace/sass-lint/lib/rules/empty-line-between-blocks.js:118:9)
    at /Users/danpurdy/workspace/sass-lint/index.js:44:27
    at Array.forEach (native)
    at Function.sassLint.lintText (/Users/danpurdy/workspace/sass-lint/index.js:43:11)
```

It seems to fail following the `@include` line here:

```sass
.foo
  @include clearfix
  .bar
    width: 32%
```

The `clearfix` mixin looks like:

```sass
@mixin clearfix
  zoom: 1

  &:before, &:after
    content: ""
    display: table

  &:after
    clear: both
```

Changing to this (empty line after `@include`) fixed the error:

```sass
.foo
  @include clearfix

  .bar
    width: 32%
```

**Comment by DanPurdy** [comment]
Thanks for the report, I've managed to replicated.

@bgriffith wanna handle this one as you went through this recently?

The issue is in this case parent.content[i - 1] is a string (`'x'` from `'clearfix'`) and so it does pass the checks but doesn't have methods attached as it's not a node obviously.

There are also some other failing cases as far as i can see.

if you include a new block directly after an empty block

```sass
.foo
  .bar
    color: red
```

no warning will be raised about the lack of space between foo and bar.
