### ISSUE TITLE
Error running `sass-lint` from CLI

### ISSUE THREAD

**Issue by mikeerickson** [sasstools/sass-lint#793]
I am just now trying to use the sass-lint CLI and am receiving the following error

```
 ~/Cirrus-Insight-Gmail-UI/ci-components  CI-ADMIN-eslint-refactor  sass-lint     
/Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/lib/rules/empty-line-between-blocks.js:65
    if (previous.is('space') || previous.is('declarationDelimiter')) {
                 ^

TypeError: previous.is is not a function
    at findNearestReturnSass (/Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/lib/rules/empty-line-between-blocks.js:65:18)
    at findNearestReturnSass (/Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/lib/rules/empty-line-between-blocks.js:80:14)
    at findNearestReturnSass (/Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/lib/rules/empty-line-between-blocks.js:70:14)
    at findNearestReturnSass (/Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/lib/rules/empty-line-between-blocks.js:70:14)
    at /Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/lib/rules/empty-line-between-blocks.js:167:23
    at Node.forEach (/Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/gonzales.js:175:83)
    at Node.<anonymous> (/Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/lib/rules/empty-line-between-blocks.js:153:16)
    at /Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/gonzales.js:299:41
    at Node.traverse (/Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/gonzales.js:279:6)
    at Node.traverse (/Users/mikeerickson/.nvm/versions/node/v5.9.1/lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/gonzales.js:284:36)
 ✘  ~/Cirrus-Insight-Gmail-UI/ci-components  CI-ADMIN-eslint-refactor  
```

**Comment by DanPurdy** [comment]
Could you please post the area of the code where this is failing. Could you please also include the other information that we ask for in the issue template such as sass-lint version etc. Thanks

**Comment by DanPurdy** [comment]
@mikeerickson would you be able to post a sample of the code you had to recreate this please?

**Comment by danielfilho** [comment]
I was having the same problem with some legacy code. follows my case:

```sass
{…}
        .delivery-date-selector
          @include clearfix
          ul
            li
              div.buttonWrapper
{…}
```

I fixed this adding an empty line before `ul`, like so:

```sass
{…}
        .delivery-date-selector
          @include clearfix

          ul
            li
              div.buttonWrapper
{…}
```

I hope this can help.

**Comment by michaelherold** [comment]
I'm working on a [CodeClimate engine to run sass-lint](https://github.com/michaelherold/codeclimate-sass-lint) and came across this error in two public repositories while testing.

* [switchboard/switchboard](https://github.com/switchboard/switchboard)
* [teambox/teambox](https://github.com/teambox/teambox)

I haven't tracked down the culprits yet, but plan to do so tomorrow or later in the week. I'll let you know what I find and will submit a pull request if I can figure it out.
