### ISSUE TITLE
Unable to find ..package.json?

### ISSUE THREAD

**Issue by mikeerickson** [sasstools/sass-lint#799]
I am receiving the following error (see below) when running CLI.

Note:  If I run command from node_modules directory and call as, it works?  Must I supply the configuration file, or is the default configuration used

```
$ sass-lint -c .sass-lint.yml -v -q
```

```
 $ ./node_modules/.bin/sass-lint -c .sass-lint.yml -v -q
module.js:341
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/mikeerickson/Documents/Projects/sandbox/node_modules/.bin/sass-lint:5:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by mikeerickson** [comment]
I think I have tracked down the issue.  In my `.sass-lint.yml` file, my files were incorrect (I was using the default config file)

```
files:
  include: '**/*.s+(a|c)ss'
```

should have been as follows

```
files:
  include: './sass/**/*.s+(a|c)ss'
```

**Comment by mikeerickson** [comment]
FYI, I took the `.sass-lint.yml` file from here

https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml

**Comment by mikeerickson** [comment]
Well, I guess things are NOT working.  When I reported it was cured above (I didnt realize I was in the actual src directory where all the .sass files are located).

So, when returning to root directory, this is what happens

```
 ~/Documents/Projects/sandbox   master ●✚ 
 $ sass-lint -v -q './sass/**/*.sass' -c .sass-lint.yml
module.js:341
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/mikeerickson/Documents/Projects/sandbox/node_modules/.bin/sass-lint:5:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
 ✘  ~/Documents/Projects/sandbox   master ●✚ 
 $ 
```

**Comment by mikeerickson** [comment]
So, again, the only way I can get this to work is cd to sass directory, then I perform the following

```
 $ sass-lint -q -v './**/*.sass'

./_disabled/test.sass
  440:1  error  Please check validity of the block starting from line #440  Fatal

./app.sass
  33:11  warning  No unit allowed for values of 0         zero-unit
  36:3   warning  Mixins should come before declarations  mixins-before-declarations
  41:3   warning  Mixins should come before declarations  mixins-before-declarations
  47:5   warning  Mixins should come before declarations  mixins-before-declarations
  50:5   warning  Mixins should come before declarations  mixins-before-declarations
  56:15  warning  No unit allowed for values of 0         zero-unit

./bootstrap.sass
  1:2  warning  Leading underscores are not allowed  clean-import-paths

✖ 8 problems (1 error, 7 warnings)

 ✘  ~/Documents/Projects/sandbox/sass   master ●✚ 
 $ 
```

**Comment by mikeerickson** [comment]
Curiously, the following command *does* work

```
 $ ./node_modules/sass-lint/bin/sass-lint.js -v -q
```

Not quite sure why this works, but other commands such as below don't work

```
$ sass-lint -v -q (with or without glob of files to process)
```

produces error of inability to locate `package.json` (see above)

**Comment by DanPurdy** [comment]
Can you provide a few details such as the platform you're on what version of sass-lint you're using globally and in your project and then any steps to recreate this.

I've installed fresh copies of everything both globally and locally and can't recreate these issues. To me it looks like an installation error as the package file it's referring to is sass-lints own package file which would be present in every install, did you use `sudo` to install sass-lint globally?

**Comment by mikeerickson** [comment]
As mentioned in other ticket, these issues have been cleared.
