### ISSUE TITLE
Different issue (bigger issue?)

### ISSUE THREAD

**Issue by mikeerickson** [sasstools/sass-lint#800]
I removed the global `sass-lint` and only have it installed at project level

Now when calling `sass-lint` (from root of project), I receive these errors

```
 $ sass-lint -c .sass-lint-sample.yml -v -q      
module.js:341
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/mikeerickson/Documents/Projects/sandbox/node_modules/.bin/sass-lint:4:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by DanPurdy** [comment]
As i mention in your other thread I feel this is an installation error on the information provided. Calling sass-lint from the root of your project the way you describe above without having it installed globally should fail. Are you sure you don't have a version of sass-lint hanging about globally somewhere, maybe a different version of node if you use nvm?

**Comment by mikeerickson** [comment]
No worries I have managed to get all things working.  You can close this (and the other issue). I would close myself right now, but this app I am using doesn't provide this functionality.
