### ISSUE TITLE
@import throws fatal error

### ISSUE THREAD

**Issue by dogmatic69** [sasstools/sass-lint#871]
sample code

    @import "bootstrap/mixins";

Output

    $ sass-lint --verbose 
    Output successfully written to ./linters/sass-lint.html
    /usr/local/lib/node_modules/sass-lint/index.js:294
        throw new Error(errorCount.count + ' errors were detected in \n- ' + errorCount.files.join('\n- '));
        ^

    Error: 1 errors were detected in 
    - contents/assets/css/_bootstrap.sass
        at Function.sassLint.failOnError (/usr/local/lib/node_modules/sass-lint/index.js:294:11)
        at detectPattern (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:33:10)
        at Object.<anonymous> (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:94:3)
        at Module._compile (module.js:556:32)
        at Object.Module._extensions..js (module.js:565:10)
        at Module.load (module.js:473:32)
        at tryModuleLoad (module.js:432:12)
        at Function.Module._load (module.js:424:3)
        at Module.runMain (module.js:590:10)
        at run (bootstrap_node.js:394:7)

What version of Sass Lint are you using?

    1.9.1

Please include any relevant parts of your configuration

    Config taken from README link, adjusted include / exclude paths

What did you do? Please include the actual source code causing the issue.

    above

What did you expect to happen?

    Not fatal, display lint errors

What actually happened? Please include any error messages given to you by Sass Lint.

    fatal, error above

If you're using a IDE plugin have you tried the CLI too?

    n/a

**Comment by DanPurdy** [comment]
You need to re read the CLI documentation and the Readme. You've probably got a rule set to severity `2` but haven't passed the `-q` or the `--no-exit` flag when you've run it from the command line. Please see [here](https://github.com/sasstools/sass-lint#cli). 

If there's something else that's not working please let us know.
