### ISSUE TITLE
Space after Comma syntax error…

### ISSUE THREAD

**Issue by tbremer** [sasstools/sass-lint#89]
**Calling module within JS file**
```
/sass-lib/node_modules/sass-lint/lib/rules/space-after-comma.js:18
        if (next.is('space')) {
                ^
TypeError: Cannot read property 'is' of undefined
    at /sass-lib/node_modules/sass-lint/lib/rules/space-after-comma.js:18:17
    at RootNode.traverseByType (/sass-lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
    at Object.module.exports.detect (/sass-lib/node_modules/sass-lint/lib/rules/space-after-comma.js:13:9)
    at /sass-lib/node_modules/sass-lint/index.js:30:25
    at Array.forEach (native)
    at Function.sassLint.lintText (/sass-lib/node_modules/sass-lint/index.js:29:9)
    at /sass-lib/node_modules/sass-lint/index.js:73:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (/sass-lib/node_modules/sass-lint/index.js:72:9)
    at Object.<anonymous> (/sass-lib/index.js:5:17)
```

**Using Gulp task**
```
/sass-lib/node_modules/sass-lint/lib/rules/space-after-comma.js:18
        if (next.is('space')) {
                ^
TypeError: Cannot read property 'is' of undefined
    at /sass-lib/node_modules/sass-lint/lib/rules/space-after-comma.js:18:17
    at RootNode.traverseByType (/sass-lib/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
    at Object.module.exports.detect (/sass-lib/node_modules/sass-lint/lib/rules/space-after-comma.js:13:9)
    at /sass-lib/node_modules/sass-lint/index.js:30:25
    at Array.forEach (native)
    at Function.sassLint.lintText (/sass-lib/node_modules/sass-lint/index.js:29:9)
    at DestroyableTransform._transform (/sass-lib/node_modules/gulp-sass-lint/index.js:32:27)
    at DestroyableTransform.Transform._read (/sass-lib/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/sass-lib/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/sass-lib/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
```

**Comment by DanPurdy** [comment]
Could you send us some of your sass/scss to reproduce this please?

**Comment by tbremer** [comment]
@DanPurdy trying to track that down now, lots of files… Any quick way to see what file is failing?

**Comment by tbremer** [comment]
Sorry, that was easier than I thought, found the file… 

Sass is:
```
@mixin app-sidebar-nav-item (
    $border: true, // Determines if the nav should have a border
    $font-size: $app-sidebar-font-size, // Sets the font size
    $padding: true, // Determines if padding should be applied
    $truncate : true, // Determines if text should be truncated
    $hover: true, // Determines if hover state should be applied
    $active: true, // Determines if active state should be applied
    $hilite: true, // Determines if hilite (hilite = currently selected or is-active state) state should be applied
    $animate: true // Determines if transition should be applied
  ) {
```

**Comment by DanPurdy** [comment]
Thanks! Have you just moved over to using sass-lint or was it only when you added the above that it broke?

**Comment by tbremer** [comment]
Testing out moving from Ruby sass-lint to your module… So, this all currently passes in brigade/scss-lint

**Comment by DanPurdy** [comment]
Awesome, will take a look. Thanks.

**Comment by tbremer** [comment]
It appears to be failing, essentially, because there isn't a 'next' on that same line (I could be reading the source wrong and I don't know much about this AST).

It'd be simple enough (but I'd worry about missing something) to wrap add another condition to the `If()` statement:
…
ast.traverseByType('operator', function (operator, i, parent) {
  var next;

  if (operator.content === ',') {
    next = parent.content[i + 1];

    if (next !== undefined && next.is('space')) {
      …
    } else {
      …
    }
    …
  }
});

return result;
…

**Comment by minamarkham** [comment]
I think this issue was related to https://github.com/tonyganch/gonzales-pe/issues/88.
