### ISSUE TITLE
Bug: clean-import-paths errors on CSS import

### ISSUE THREAD

**Issue by minamarkham** [sasstools/sass-lint#95]
Running gulp task with Sass Lint 1.1.0

The following code
```
@if variable-exists(google-fonts-url) {
  @import url($google-fonts-url);
}
```

throws this error
```
/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/clean-import-paths.js:36
          var importPath = stripQuotes(parent.first('string').content),
                                                             ^
TypeError: Cannot read property 'content' of undefined
    at /Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/clean-import-paths.js:36:62
    at Node.traverse (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/basic-node.js:1:3265)
    at Node.traverse (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/basic-node.js:1:3407)
    at /Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/clean-import-paths.js:33:15
    at RootNode.traverseByType (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/node_modules/gonzales-pe/lib/node/root-node.js:1:1739)
    at Object.module.exports.detect (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/rules/clean-import-paths.js:32:9)
    at /Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/index.js:30:25
    at Array.forEach (native)
    at Function.sassLint.lintText (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/index.js:29:9)
    at DestroyableTransform._transform (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/index.js:32:27)
```

**Comment by bgriffith** [comment]
Thanks mina, I'll take a look.
